version: "3.8"
services:
  postgres:
    container_name: postgres_cars
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db:
    driver: local