version: "3.8"
services:
  postgres:
    container_name: postgres_cars
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.production
  server:
    build: .
    depends_on:
      - postgres
    image: carapi_server
    env_file:
      - .env.production
    ports:
      - "3000:3000"

volumes:
  db:
    driver: local
